title: Ian Barnes
author: Ian Barnes
description: Personal web site of Ian Barnes

url: "https://www.ianbarnes.me.uk"

timezone: Europe/Paris
date_format: "%Y-%m-%d %H:%M:%S %Z"

plugins:
  - jekyll-feed

markdown: kramdown
kramdown:
  extensions: ["smart", "footnotes"]

rss: true
show_excerpts: true

header_pages:
  - index.md
  - cv.md
  - projects.md
  - blog.md
  - contact.md

exclude: [Makefile, README.md]
